<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>THE Classic bug (No available USB device found with matching PID/VID)</title>
    <link>https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439</link>
    <description>Hello everybody !

I&#39;m a axoloti newbie. The Axoloti software console always write _No available USB device found with matching PID/VID_. But the messages before have changed.

I&#39;m on Win7 X64. My USB cable is working, I did rescue firmware, WinUSB install, Zadig, external powering, many unplugging re-plugging... but I still get infamous _No available USB device found with matching PID/VID_

Any suggestion ? 


Axoloti version : 1.0.12-2-0-g60a2f99  build time : 08/04/2018 20:20:07 CEST
Link to firmware CRC E95BAC96
Status: factory (1.0.12,anon) : OK  ( 1.0.12,clean )
Status : home : OK
Status: community (1.0.12,anon) : OK  ( 1.0.12,clean )
No available USB device found with matching PID/VID
search path : C:\Users\Toyoto\Documents\axoloti\axoloti-factory\objects
search path : C:\Users\Toyoto\Documents\axoloti\objects
search path : C:\Users\Toyoto\Documents\axoloti\axoloti-contrib\objects
finished loading objects</description>
    
    <lastBuildDate>Fri, 24 Apr 2020 12:01:50 +0000</lastBuildDate>
    <category>Helpdesk</category>
    <atom:link href="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>THE Classic bug (No available USB device found with matching PID/VID)</title>
        <dc:creator><![CDATA[@jcgriggs John Griggs]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/jcgriggs">@jcgriggs</a> wrote:</p>
          <blockquote>
              <p>Sorry - I don't have any real insight other than recognizing the USB error code from something else I worked on.</p>

<p>Best of luck,<br>   John</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/11">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/11</link>
        <pubDate>Fri, 24 Apr 2020 12:01:50 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-5439-11</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439.rss">THE Classic bug (No available USB device found with matching PID/VID)</source>
      </item>
      <item>
        <title>THE Classic bug (No available USB device found with matching PID/VID)</title>
        <dc:creator><![CDATA[@sebiiksbcs Sebastian]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/sebiiksbcs">@sebiiksbcs</a> wrote:</p>
          <blockquote>
              <p>Thank you jcgriggs, external power, faulty USB cable etc. was among the things I've tested, also curious is the fact that Axoloti in DFU mode connects and flashes fine but isn't recognized after reboot.</p>

<p>I've come to the temporary conclusion that the fault may have to do with the current linux kernel version, that or the USB ports on my computer somehow became faulty.</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/10">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/10</link>
        <pubDate>Fri, 24 Apr 2020 07:55:28 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-5439-10</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439.rss">THE Classic bug (No available USB device found with matching PID/VID)</source>
      </item>
      <item>
        <title>THE Classic bug (No available USB device found with matching PID/VID)</title>
        <dc:creator><![CDATA[@jcgriggs John Griggs]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/jcgriggs">@jcgriggs</a> wrote:</p>
          <blockquote>
              <p>USB 110 is an incomplete transfer error, usually caused when the device power dips during the transfer.  Make sure the Axoloti is getting enough power - no other devices on hub, etc.</p>

<p>Hope this helps,<br>   John</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/9">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/9</link>
        <pubDate>Thu, 23 Apr 2020 16:56:33 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-5439-9</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439.rss">THE Classic bug (No available USB device found with matching PID/VID)</source>
      </item>
      <item>
        <title>THE Classic bug (No available USB device found with matching PID/VID)</title>
        <dc:creator><![CDATA[@sebiiksbcs Sebastian]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/sebiiksbcs">@sebiiksbcs</a> wrote:</p>
          <blockquote>
              <p>I've been getting this type of error trying to connect to Axoloti Core on Ubuntu 18.04 out of the blue for days now without previously having changed anything in my setup ("although not "error -32" but error -110" for me)...</p>

<p>I am able to connect to STM32 in DFU mode at all times and flash firmware with any USB cables I tried, but can't connect to the Axoloti Core after reboot...</p>

<p>Tried all of the possible solutions online I could find, still no luck. At one point the connection came back for about an hour, then back to the error... People in forums say it could be a hardware fault at the host USB port but any other USB devices connect without problems...</p>

<p>Anyone have a tip?</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/8">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/8</link>
        <pubDate>Thu, 23 Apr 2020 07:13:02 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-5439-8</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439.rss">THE Classic bug (No available USB device found with matching PID/VID)</source>
      </item>
      <item>
        <title>THE Classic bug (No available USB device found with matching PID/VID)</title>
        <dc:creator><![CDATA[@deadsy Jason T Harris]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/deadsy">@deadsy</a> wrote:</p>
          <blockquote>
              <p>Another datapoint (this time on Linux/ubuntu 18.04):</p>

<pre><code>[   83.507607] usb 1-14.4: new low-speed USB device number 18 using xhci_hcd
[   83.587618] usb 1-14.4: device descriptor read/64, error -32
[   83.775540] usb 1-14.4: device descriptor read/64, error -32
[   83.963448] usb 1-14.4: new low-speed USB device number 19 using xhci_hcd
[   84.043433] usb 1-14.4: device descriptor read/64, error -32
[   84.231360] usb 1-14.4: device descriptor read/64, error -32
[   84.339591] usb 1-14-port4: attempt power cycle
[   85.507169] usb 1-14-port4: Cannot enable. Maybe the USB cable is bad?
[   86.358866] usb 1-14-port4: Cannot enable. Maybe the USB cable is bad?
[   86.359176] usb 1-14-port4: unable to enumerate USB device</code></pre>

<p>And indeed it was (one cable swap later)....</p>

<pre><code>[  138.840224] usb 1-14.4: new full-speed USB device number 22 using xhci_hcd
[  138.942059] usb 1-14.4: New USB device found, idVendor=16c0, idProduct=0442
[  138.942065] usb 1-14.4: New USB device strings: Mfr=1, Product=5, SerialNumber=3
[  138.942069] usb 1-14.4: Product: Axoloti Core
[  138.942073] usb 1-14.4: Manufacturer: Axoloti
[  138.942077] usb 1-14.4: SerialNumber: 0045001E3237511832333637</code></pre>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/7">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/7</link>
        <pubDate>Tue, 26 Feb 2019 16:51:47 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-5439-7</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439.rss">THE Classic bug (No available USB device found with matching PID/VID)</source>
      </item>
      <item>
        <title>THE Classic bug (No available USB device found with matching PID/VID)</title>
        <dc:creator><![CDATA[@terenss Terence]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/terenss">@terenss</a> wrote:</p>
          <blockquote>
              <p>I installed Windows 10 because Win7 seems to have trouble with Axoloti. It worked like a charm... at the begining. When I plugged in an headphone, I got a java error and now I have the same message again ("No available USB device found with matching PID/VID")</p>

<p>Thanks for the link. I will use the Zadig.exe in order to reload firmware. The board isn't visible in normal mode so I boot in rescue mode (S1), unplug, plug again in normal mode and then windows loads the core. And NOW IT IS WORKING !!!! GREAT  !!</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/6">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/6</link>
        <pubDate>Tue, 26 Feb 2019 15:45:24 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-5439-6</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439.rss">THE Classic bug (No available USB device found with matching PID/VID)</source>
      </item>
      <item>
        <title>THE Classic bug (No available USB device found with matching PID/VID)</title>
        <dc:creator><![CDATA[@UHF]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/uhf">@UHF</a> wrote:</p>
          <blockquote>
              <p>There seems to be a number of issues that can cause this. Have you looked at this thread?:<br><aside class="quote" data-post="1" data-topic="117">
  <div class="title">
    <div class="quote-controls"></div>
    <img alt="" width="20" height="20" src="/letter_avatar_proxy/v2/letter/0/c6cbf5/40.png" class="avatar">
    <a href="//community.axoloti.com/t/win-7-no-usb-found-with-matching-pid-vid/117?source_topic_id=5439" rel="nofollow noopener">Win 7 no usb found with matching PID/VID</a> <a class="badge-wrapper  bullet" href="/c/helpdesk"><span class="badge-category-bg" style="background-color: #9EB83B;"></span><span style="color: #FFFFFF;" class="badge-category clear-badge" title='This category is for reporting issues and bugsPlease use other categories for discussions on features or questions or "how to?"'>Helpdesk</span></a>
  </div>
  <blockquote>
    Hoi.  I recieved my axoloti yesterday. The software reports a problem with the driver and can not connect, 

DId the installation as told in the guide. Axoloti core is visible in Win 7 Device Manager,  The software found no matching PID/VID., when i try to connect.  (USB is connected off course and the lights on the board blink at start up) 

When i choose select device, it sees the axo core and the usb port, at CPU ID it reads: not available: driver not installed. 

Re-installing the driver did…
  </blockquote>
</aside>
</p>

<p>Someone even had a problem with antivirus software blocking it.</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/5">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/5</link>
        <pubDate>Sun, 24 Feb 2019 13:37:30 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-5439-5</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439.rss">THE Classic bug (No available USB device found with matching PID/VID)</source>
      </item>
      <item>
        <title>THE Classic bug (No available USB device found with matching PID/VID)</title>
        <dc:creator><![CDATA[@terenss Terence]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/terenss">@terenss</a> wrote:</p>
          <blockquote>
              <p>Hello UHF,</p>

<p>It is a data cable. I've been able to successfully upload firmware on my axoloti with it. I've tried again with another high quality Anker data cable without success.</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/4">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/4</link>
        <pubDate>Fri, 22 Feb 2019 09:10:34 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-5439-4</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439.rss">THE Classic bug (No available USB device found with matching PID/VID)</source>
      </item>
      <item>
        <title>THE Classic bug (No available USB device found with matching PID/VID)</title>
        <dc:creator><![CDATA[@UHF]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/uhf">@UHF</a> wrote:</p>
          <blockquote>
              <p>The USB cable IS a data cable and not a charging cable?</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/3">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/3</link>
        <pubDate>Fri, 22 Feb 2019 06:16:00 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-5439-3</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439.rss">THE Classic bug (No available USB device found with matching PID/VID)</source>
      </item>
      <item>
        <title>THE Classic bug (No available USB device found with matching PID/VID)</title>
        <dc:creator><![CDATA[@terenss Terence]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/terenss">@terenss</a> wrote:</p>
          <blockquote>
              <p>And I'm not using any hub on this USB port</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/2">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/2</link>
        <pubDate>Tue, 19 Feb 2019 15:40:49 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-5439-2</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439.rss">THE Classic bug (No available USB device found with matching PID/VID)</source>
      </item>
      <item>
        <title>THE Classic bug (No available USB device found with matching PID/VID)</title>
        <dc:creator><![CDATA[@terenss Terence]]></dc:creator>
        <description><![CDATA[
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/u/terenss">@terenss</a> wrote:</p>
          <blockquote>
              <p>Hello everybody !</p>

<p>I'm a axoloti newbie. The Axoloti software console always write <em>No available USB device found with matching PID/VID</em>. But the messages before have changed.</p>

<p>I'm on Win7 X64. My USB cable is working, I did rescue firmware, WinUSB install, Zadig, external powering, many unplugging re-plugging... but I still get infamous <em>No available USB device found with matching PID/VID</em></p>

<p>Any suggestion ? </p>

<p>Axoloti version : 1.0.12-2-0-g60a2f99  build time : 08/04/2018 20:20:07 CEST<br>Link to firmware CRC E95BAC96<br>Status: factory (1.0.12,anon) : OK  ( 1.0.12,clean )<br>Status : home : OK<br>Status: community (1.0.12,anon) : OK  ( 1.0.12,clean )<br>No available USB device found with matching PID/VID<br>search path : C:\Users\Toyoto\Documents\axoloti\axoloti-factory\objects<br>search path : C:\Users\Toyoto\Documents\axoloti\objects<br>search path : C:\Users\Toyoto\Documents\axoloti\axoloti-contrib\objects<br>finished loading objects</p>
          </blockquote>
          <p><a href="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/1">Read full topic</a></p>
        ]]></description>
        <link>https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439/1</link>
        <pubDate>Mon, 18 Feb 2019 17:00:41 +0000</pubDate>
        <guid isPermaLink="false">community.axoloti.com-post-5439-1</guid>
        <source url="https://sebiik.github.io/community.axoloti.com.backup/t/the-classic-bug-no-available-usb-device-found-with-matching-pid-vid/5439.rss">THE Classic bug (No available USB device found with matching PID/VID)</source>
      </item>
  </channel>
</rss>
